openapi: "3.0.0"
info:
  description: "Codegen for demo service"
  version: "0.0.1"
  title: "Demo Service Specification"
  contact:
    email: "aserroukh@atsistemas"
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: "transaction"
    description: "User tag for demo purposes"
servers:
  - url: http://localhost:8000/
    description: "local host"
paths:
  #### Transaction ####
  /transaction:
    post:
      tags:
        - "transaction"
      summary: create new Transaction
      operationId: createTransaction
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: "#/components/schemas/Transaction"
      responses:
        200:
          description: succes
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Status"


  /transaction/{iban}:
    get:
      tags:
        - "transaction"
      summary: "Retrieves User by ID"
      operationId: "findTransactionByIban"
      parameters:
        - name: "iban"
          in: "path"
          description: "retrieves user by user id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Retrieves family members by person id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
  #### Transaction ####
  /status/{iban}:
    get:
      tags:
        - "transaction"
      summary: "Retrieves User by ID"
      operationId: "getTransactionsByIban"
      parameters:
        - name: "iban"
          in: "path"
          description: "retrieves user by user id"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Retrieves family members by person id"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'


components:
  schemas:
    Transaction:
      type: "object"
      required:
        - "reference"
        - "iban"
        - "date"
        - "amount"
        - "fee"
        - "description"
      properties:
        reference:
          type: "string"
          example: "12345A"
        iban:
          type: "string"
          example: "ES9820385778983000760236"
        date:
          type: "string"
          example: "ES9820385778983000760236"
        amount:
          type: "number"
          example: "193.38"
        fee:
          type: "integer"
          example: "3.18"
        description:
          type: "string"
          example: "Restaurant payment"

    Status:
      type: "object"
      required:
        - "reference"
        - "status"
        - "amount"
        - "fee"

      properties:
        reference:
          type: "string"
          example: "12345A"
        status:
          type: "string"
          enum: [PENDING, SETTLED, FUTURE, INVALID]
          example: "PENDING"
        amount:
          type: "string"
          example: "12345A"
        fee:
          type: "string"
          example: "12345A"



